<?php

/**
 * ClassifyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClassifyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClassifyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Classify');
    }
    
    public function getAllClassifies(){
    	 $q = Doctrine_Query::create()
    	 ->from("Classify c")
    	 ->where("c.active = 1");
    	 
    	 return $q->execute();
    }
}