<?php

/**
 * PictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PictureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Picture');
    }
    
    public function getHomePicture($num){
    	if($num == null || $num == 0 ||!is_numeric($num)){
    		$num = 20;
    	}
    	$q = Doctrine_Query::create()
    	->from("Picture p")
    	->where("p.active = 1")
    	->limit($num);
    	
    	return $q->execute();
    }
    
    public function getClassifyPicture($classifyId, $num){
    	if($num == null || $num == 0 ||!is_numeric($num)){
    		$num = 20;
    	}
    	if($classifyId == null || $classifyId == 0 ||!is_numeric($num)){
    		$classifyId = 1;
    	}
    	$q = Doctrine_Query::create()
    	->from("Picture p")
    	->where("p.active = 1")
    	->andWhere("p.classify_id = ?", $classifyId)
    	->limit($num);
    	
    	return $q->execute();
    }
    
    public function getClassifyAndStylePicture($classifyId, $style, $num){
    	if($num == null || $num == 0 ||!is_numeric($num)){
    		$num = 20;
    	}
    	if($classifyId == null || $classifyId == 0 ||!is_numeric($classifyId)){
    		$classifyId = 1;
    	}
    	if($style == null || $style == 0 ||!is_numeric($style)){
    		$style = 1;
    	}
    	$q = Doctrine_Query::create()
    	->from("Picture p")
    	->where("p.active = 1")
    	->andWhere("p.classify_id = ?", $classifyId)
    	->andWhere("p.style_id = ?", $style)
    	->limit($num);
    	
    	return $q->execute();
    }
    
	public function getRecomPicture($num){
    	if($num == null || $num == 0 ||!is_numeric($num)){
    		$num = 20;
    	}
    	$q = Doctrine_Query::create()
    	->from("Picture p")
    	->where("p.active = 1")
    	->andWhere("p.isidea = 1")
    	->limit($num);
    	
    	return $q->execute();
    }
}