<?php

/**
 * StyleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StyleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StyleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Style');
    }
    
    public function getAllStyles(){
    	$q = Doctrine_Query::create()
    	->from("Style s")
    	->where("s.active = 1");
    	
    	return $q->execute();
    }
}