<?php

/**
 * UserPictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserPictureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserPictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserPicture');
    }
    
    public function getObject($userId, $pictureId, $action){
    	$q = Doctrine_Query::create()
    	->from("UserPicture u")
    	->where("u.user_id = ?", $userId)
    	->andWhere("u.picture_id = ?", $pictureId)
    	->andWhere("u.action = ?", $action);
    }
}