<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }
    
    public function getUserByNameAndPasswd($username, $password){
    	$q = Doctrine_Query::create()
    	->from("User u")
    	->where("u.name = ?", $username)
    	->andWhere("u.password = ?", $password)
    	->andWhere("u.active = 1");
    	
    	return $q->fetchOne();
    }
    
    public function getUserByName($username){
    	$q = Doctrine_Query::create()
    	->from("User u")
    	->where("u.name = ?", $username)
    	->andWhere("u.active = 1");
    	
    	return $q->fetchOne();
    }
}