<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/06/29 10:41:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=home',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
